name: flutter_facebook_clone
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: "^0.9.2"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/facebook_clone_logo.png"
  android: true
  ios: false
  web: false
  fullscreen: true

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/facebook_clone_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - fonts/
    
flutter_intl:
  enabled: true
